#!/usr/bin/env bash
#set -x
#echo "++ gateway ++"

#chirpstack-gateway-bridge
if [ -d "/share/chirp2mqtt/etc/chirpstack-gateway-bridge" ]; then
    cp /share/chirp2mqtt/etc/chirpstack-gateway-bridge/* /etc/chirpstack-gateway-bridge
fi
exec chirpstack-gateway-bridge
