#!/usr/bin/env bash
#echo "++ chirpstack ++"
#set -x

INITIALIZED="/data/chirpstack_tables_initialized"
BACKUPDONE="/data/chirpstack_backup_done"
EXTPATH="/share/chirp2mqtt"
DBFILE="chirp_db"
CONFILE="/data/options.json"

backup_db() {
    if ! [ -d "$EXTPATH" ]; then
        mkdir $EXTPATH
        chown postgres:postgres $EXTPATH
    fi
    su-exec postgres pg_dump chirpstack  -w > $EXTPATH/$DBFILE
    if [ $? -eq 0 ]; then
        echo Backup done to $EXTPATH/$DBFILE, waiting for add-on restart
        touch $BACKUPDONE
        while true
        do
            sleep 300
        done
    else
        echo Backup failed, check logs
    fi
}

restore_db() {
    if [ -f "$EXTPATH/$DBFILE" ]; then
        su-exec postgres psql -c "drop database if exists chirpstack;"
        su-exec postgres psql -c "drop role if exists chirpstack;"
        su-exec postgres psql -c "create role chirpstack with login password 'chirpstack';"
        su-exec postgres psql -c "create database chirpstack with owner chirpstack;"
        su-exec postgres psql -d chirpstack < $EXTPATH/$DBFILE >/dev/null
        if [[ $? -eq 0 ]]; then
            touch $INITIALIZED
            mv $EXTPATH/$DBFILE $EXTPATH/$DBFILE.restored
            echo Database restored, backup file renamed to $DBFILE.restored
        else
            echo Database restored failed, check logs for details
        fi
    else
        echo Database backup file $EXTPATH/$DBFILE could not be processed
    fi
}

# set user name in chirpstack/bridge and region configuration files
MQTT_USER=$(jq --raw-output '.mqtt_user // empty' $CONFILE)
sed -i -r  's|username.*=.*".*"|username = "'$MQTT_USER'"|' /etc/chirpstack/chirpstack.toml
sed -i -r  's|username.*=.*".*"|username = "'$MQTT_USER'"|' /etc/chirpstack/region_*.toml
sed -i -r  's|username.*=.*".*"|username = "'$MQTT_USER'"|' /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml

# set password in chirpstack/bridge and region configuration files
MQTT_PASSWORD=$(jq --raw-output '.mqtt_password // empty' $CONFILE)
sed -i -r  's|password.*=.*".*"|password = "'$MQTT_PASSWORD'"|' /etc/chirpstack/chirpstack.toml
sed -i -r  's|password.*=.*".*"|password = "'$MQTT_PASSWORD'"|' /etc/chirpstack/region_*.toml
sed -i -r  's|password.*=.*".*"|password = "'$MQTT_PASSWORD'"|' /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml

# set region in chirpstack and gateway configuration files
LORA_REGION=$(jq --raw-output '.lora_region // empty' $CONFILE)
sed -i 's|"eu868"|"'$LORA_REGION'"|' /etc/chirpstack/chirpstack.toml
sed -i 's|eu868/|'$LORA_REGION'/|' /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
echo Lora region $LORA_REGION selected

# set secret in chirpstack configuration file
CHIRPSTACK_SECRET=$(jq --raw-output '.chirpstack_secret // empty' $CONFILE)
sed -i -r  's|secret.*=.*".*"|secret = "'$CHIRPSTACK_SECRET'"|' /etc/chirpstack/chirpstack.toml
echo ChirpStack secret $CHIRPSTACK_SECRET

DB_ACTION=$(jq --raw-output '.database_actions // empty' $CONFILE)
echo Database action: $DB_ACTION

if [ "$DB_ACTION" = "Backup and restore" ]; then
    if [ -f "$BACKUPDONE" ]; then
        restore_db
    else
        backup_db
    fi
fi

if [ -f "$BACKUPDONE" ]; then
    rm $BACKUPDONE
fi

if [ "$DB_ACTION" = "Restore" ]; then
    restore_db
fi

if [ "$DB_ACTION" = "Backup" ]; then
    backup_db
fi

if ! [ -f "$INITIALIZED" ]; then
    su-exec postgres psql -c "drop database if exists chirpstack;"
    su-exec postgres psql -c "drop role if exists chirpstack;"
    su-exec postgres psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc -f /etc/postgres_chirp.sql
    if [ -d "/data/temp" ]; then
        rm -r /data/temp
    fi
    mkdir /data/temp
    git clone https://github.com/brocaar/lorawan-devices /data/temp/lorawan-devices >/dev/null 2>/dev/null
    chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /data/temp/lorawan-devices >/dev/null
    if [[ $? -eq 0 ]]; then
        touch $INITIALIZED
    fi
    rm -r /data/temp
fi

#chirpstack -c /etc/chirpstack
if [ -d "$EXTPATH/etc/chirpstack" ]; then
    cp $EXTPATH/etc/chirpstack/* /etc/chirpstack
fi

#ls /package/admin/s6-overlay/command/with-contenv -l
#bashio /usr/local/bin/upd_chirpstack_conf
su-exec postgres psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc -f /etc/delete_ha_api_keys.sql

signal_chirpstack &
chirpstack -c /etc/chirpstack
